### ISSUE TITLE
Incremental build

### ISSUE THREAD

**Issue by dreikanter** [dreikanter/public-static#61]
This is a big one!
- On each [re]build save cache index to a separate file `build.yaml` inside current directory or use explicitly defined path from command line arguments.
- Consider if the default build mode should be **rebuild** or **force build** (`pub build -r/-f`).
- Use the index in rebuild mode to determine changed files.
- Generate only changed files in rebuild mode.
- If existing `build.yaml` contains a record which source file name not present in the new `build.yaml` contents, the destination file for this record should be deleted.
- Posts update should additionally trigger index, relevant tags, and feed rebuild.
- Any page update should trigger `sitemap.xml` rebuild.
- Consider to use md5 or other hash instead of time stamps.

Sample `build.yaml` contents:

``` yaml
generator-version: 0.7.5
gen-time: 23850283409820349
files:
- source: assets/css/custom.css
  dest: css/custom.css
  updated: 2013-08-09 12:17:20
- source: posts/20100909-hello.md
  dest: 2010/09/09/hello.html
  updated: 2013-08-09 12:17:20
- source: posts/20100909-news.md
  dest: 2010/09/09/news.html
  updated: 2013-08-09 12:17:20
- source: pages/about.md
  dest: about.html
  updated: 2013-08-09 12:17:20
```
