### ISSUE TITLE
Templates text customization thru a group of configuration parameters

### ISSUE THREAD

**Issue by dreikanter** [dreikanter/public-static#9]
Templates could use configuration parameters declared in `template_params` dictionary.

``` yaml
- template_params:
    next_page: Future →
    prev_page: ← Past
    ...
```
